platform :ios, '8.0'
inhibit_all_warnings!
use_frameworks!
target 'TXTJSMAPP' do 
pod 'AFNetworking'
pod 'ReactiveObjC'
pod 'Masonry'
pod 'YYModel'
pod 'FDFullscreenPopGesture'
pod 'MJRefresh'
pod 'WechatOpenSDK'
pod 'SDWebImage/Core'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/aliyun/aliyun-specs.git'
pod 'AlicloudMAN'

end
